#!/bin/bash
#
# - - -
# authority: CIS/6.6
# authority: CIS5/7.6
# description: Scans HFS filesystems for world-writable files
# - - -
set -e

. `dirname $0`/../../lib/functions

check()
{
    # Anything written to stdout or stderr indicates a compliance problem.

    echo "))= World-writable files on HFS file systems:"
    # Note:  /nsr/tmp/xxx automagically reappear, world-writable. Excuse them.
    parts=$(mount | awk '$4 ~ /hfs/ { print $3 }')
    for part in $parts
    do 
        find $part -xdev \( -path /nsr/tmp -prune \) -o \( -type f \( -perm -0002 -a ! -perm -1000 \) -ls \)
    done 
}

case "$1" in 
    check)
        check;
        ;;
    *)
        echo "Usage: $0 {check|fix}"
        ;;
esac
exit 0

