#!/bin/sh
PATH=$PATH:/bin:/usr/bin:/sbin:/usr/sbin
automatic=$1
options=$2
RH=`cat /etc/redhat-release | awk '{print $7}'|cut -d. -f1`

menu1=0; menu2=0; menu3=0; menu4=0; menu5=0; menu6=0; menu7=0
flag1=0; flag2=0; flag3=0; flag4=0; flag5=0; flag6=0; flag7=0
if test "$automatic" = "1" 
then
    if test "$options" = "1"
    then
        menu1=1; menu2=0; menu3=0; menu4=0; menu5=0; menu6=0; menu7=0
    elif test "$options" = "2"
    then
        menu1=1; menu2=0; menu3=0; menu4=0; menu5=0; menu6=0; menu7=0
    else
        echo "exited in parsing options in section 2 menus"
        exit
    fi
fi
until test "$console_in" = "0"
do
    #clear
    echo "        CIS LINUX Benchmark v2.0"
    echo "             Section 2  Menu"
    echo 
    if test "$menu1" = 1
    then
        echo "_X_ (1) 2.1 Disable inetd services "
    else
        echo "___ (1) 2.1 Disable inetd services "
    fi
    if test "$menu2" = 1
    then
        echo "_X_ (2) 2.2 Only enable telnet if absolutely necessary "
    else
        echo "___ (2) 2.2 Only enable telnet if absolutely necessary "
    fi
    if test "$menu3" = 1
    then
        echo "_X_ (3) 2.3 Only enable FTP if absolutely necessary "
    else
        echo "___ (3) 2.3 Only enable FTP if absolutely necessary "
    fi
    if test "$menu4" = 1
    then
        echo "_X_ (4) 2.4 Only enable rlogin/rsh/rcp if absolutely necessary "
    else
        echo "___ (4) 2.4 Only enable rlogin/rsh/rcp if absolutely necessary "
    fi
    if test "$menu5" = 1
    then
        echo "_X_ (5) 2.5 Only enable TFTP if absolutely necessary "
    else
        echo "___ (5) 2.5 Only enable TFTP if absolutely necessary "
    fi
    if test "$menu6" = 1
    then
        echo "_X_ (6) 2.6 Only enable IMAP if absolutely necessary "
    else
        echo "___ (6) 2.6 Only enable IMAP if absolutely necessary "
    fi
    if test "$menu7" = 1
    then
        echo "_X_ (7) 2.7 Only enable POP if absolutely necessary "
    else
        echo "___ (7) 2.7 Only enable POP if absolutely necessary "
    fi
        echo "    (0)  Back to Main Menu"
        echo " Selection => "
    
    if test "$automatic" = "1"
        then
        echo "automatic opted"
    else
        read console_in
    fi   

    if ((test "$console_in" = "1" || test "$menu1" = "1" ) && ( test "$flag1" != "1") )
    then
        echo "2.1 Disable standard services"
        if [ -e /etc/xinetd.d ]; then
            cd /etc/xinetd.d 
            for file in *
            do 
                #/sbin/chkconfig $file off 
                sed -i 's/^[^#]*disable\W*=.*$/\tdisable = yes/' $file
            done
        fi
        echo "Section 2.1 completed."
        menu1=1
        flag1=1
    fi

    if ((test "$console_in" = "2" || test "$menu2" = "1") && ( test "$flag2" != "1") )
    then
        [ -e /etc/xinetd.d ] && cd /etc/xinetd.d
        for files in *telnet
        do
            awk '/.*disable.*=.*yes/ {print "\tdisable=no";next};{print;next}' $files >$files.newCIS
            /bin/mv $files.newCIS $files
        done

        echo "Section 2.2 completed."
        menu2=1
        flag2=1
    fi

    if ((test "$console_in" = "3" || test "$menu3" = "1") && ( test "$flag3" != "1") )
    then
        [ -e /etc/xinetd.d ] && cd /etc/xinetd.d
        for files in *ftpd* *gssftp*
        do
            if [ -e $files ]; then
                awk '/.*disable.*=.*yes/ {print "\tdisable=no";next};{print;next}' $files >$files.newCIS
                /bin/mv $files.newCIS $files
            fi
        done
        echo "Section 2.3 completed."
        menu3=1
        flag3=1
    fi
    
    if ((test "$console_in" = "4" || test "$menu4" = "1") && ( test "$flag4" != "1") )
    then
        [ -e /etc/xinetd.d ] && cd /etc/xinetd.d
        for files in *shell rsh *login
        do
            if [ -e $files ]; then 
                awk '/.*disable.*=.*yes/ {print "\tdisable=no";next};{print;next}' $files >$files.newCIS
                /bin/mv $files.newCIS $files
            fi
        done
        echo "Section 2.4 completed."
        menu4=1
        flag4=1
    fi

    if ((test "$console_in" = "5" || test "$menu5" = "1") && ( test "$flag5" != "1") )
    then
        [ -e /etc/xinetd.d ] && cd /etc/xinetd.d
        for files in tftp
        do
            if [ -e $files ]; then
                awk '/.*disable.*=.*yes/ {print "\tdisable=no";next};{print;next}' $files >$files.newCIS
                /bin/mv $files.newCIS $files
            fi
        done
        if [ ! -d "/tftpboot" ] ; then 
            /bin/mkdir -m 0755 /tftpboot && \
            /bin/chown root:root /tftpboot 
        fi 
        echo "Section 2.5 completed."
        menu5=1
        flag5=1
    fi
    
    if ((test "$console_in" = "6" || test "$menu6" = "1") && ( test "$flag6" != "1") )
    then
    [ -e /etc/xinetd.d ] && cd /etc/xinetd.d
        for files in imap
        do
            if [ -e $files ]; then
                awk '/.*disable.*=.*yes/ {print "\tdisable=no";next};{print;next}' $files >$files.newCIS
                /bin/mv $files.newCIS $files
            fi
        done

        echo "Section 2.6 completed."
        menu6=1
        flag6=1
    fi

    if ((test "$console_in" = "7" || test "$menu7" = "1") && ( test "$flag7" != "1") )
    then
        [ -e /etc/xinetd.d ] && cd /etc/xinetd.d
        for files in pop3s
        do
            if [ -e $files ]; then
                awk '/.*disable.*=.*yes/ {print "\tdisable=no";next};{print;next}' $files >$files.newCIS
                /bin/mv $files.newCIS $files
            fi
        done

        echo "Section 2.7 completed."
        menu7=1
        flag7=1
    fi
    if test "$automatic" = "1" 
    then
        console_in=0
    fi

done
