#!/bin/sh
PATH=$PATH:/bin:/usr/bin:/sbin:/usr/sbin
automatic=$1
options=$2

menu1=0; menu2=0; menu3=0; menu4=0; menu5=0; menu6=0; menu7=0
flag1=0; flag2=0; flag3=0; flag4=0; flag5=0; flag6=0; flag7=0
if test "$automatic" = "1"
then
    if test "$options" = "1"
    then
        menu1=1; menu2=1; menu3=1; menu4=0; menu5=0; menu6=0; menu7=0
    elif test "$options" = "2"
    then
        menu1=1; menu2=1; menu3=1; menu4=0; menu5=0; menu6=0; menu7=0
    else
        echo "exited in parsing options in section 5 menus"
        exit
    fi
fi


until test "$console_in" = "0"
do
    #clear
    echo "        CIS MACOS Benchmark v2.0"
    echo "             Section 3  Menu"
    echo 
    if test "$menu1" = 1 
    then
        echo "_X_ (1) 3.1 Capture messages sent to syslog AUTHPRIV facility "
    else
        echo "___ (1) 3.1 Capture messages sent to syslog AUTHPRIV facility "
    fi
    if test "$menu2" = 1 
    then
        echo "_X_ (2) 3.2 direct copy of all logs to syslog server"
    else
        echo "___ (2) 3.2 Direct copy of all logs to syslog server"
    fi
    if test "$menu3" = 1 
    then
        echo "_X_ (3) 3.3 Confirm permissions on system log files"
    else
        echo "___ (3) 3.3 Confirm permissions on system log files"
    fi
    echo "    (0)  Back to Main Menu"
    echo " Selection => "
     
    if test "$automatic" = "1"
    then
        echo "automatic opted"
    else
        read console_in
    fi   
    
    if ((test "$console_in" = "1" || test "$menu1" = "1" ) && ( test "$flag1" != "1") )
    then
        if [ -f /etc/syslog.conf ] 
        then
            if [ `grep -c 'var.log.secure' /etc/asl.conf` -eq 0 ] 
            then 
                sed -i'.preCIS' '/Facility auth/d' /etc/asl.conf
                cat >> /etc/asl.conf <<_EOF_

# Rules for /var/log/secure.log
> secure mode=0640 format=bsd rotate=seq compress file_max=5M all_max=50M
? [= Facility auth] [<= Level info] file secure
? [= Facility authpriv] [<= Level info] file secure
? [= Facility remoteauth] [<= Level info] file secure
_EOF_
            fi 
        fi
        touch /var/log/secure 
        chown root:admin /var/log/secure 
        chmod 640 /var/log/secure 
        echo "Section 3.1 completed."
        menu1=1
        flag1=1
    fi

	if ((test "$console_in" = "2" || test "$menu2" = "1" ) && ( test "$flag2" != "1") )
    then
        if [ `grep -c '^\*\.[debug|\*].*\@lhcsyslog.*' /etc/syslog.conf` -eq 0 ] 
        then 
            echo "*.*	@lhcsyslog.nlm.nih.gov" >>/etc/syslog.conf 
        fi 
        echo "Section 3.2 completed."
        menu2=1
	    flag2=1
    fi

    if ((test "$console_in" = "3" || test "$menu3" = "1" ) && ( test "$flag3" != "1") )
    then
#      cd /var/log 
#      /bin/chmod o-w boot.log* cron* dmesg ksyms* httpd/* \
#            maillog* messages* news/* pgsql rpmpkgs* samba/* \
#            scrollkeeper.log secure* spooler* squid/* vbox/* wtmp                        2> /dev/null
#      /bin/chmod o-rx boot.log* cron* maillog* messages* pgsql \
#            secure* spooler* squid/*                                                      2> /dev/null
#      /bin/chmod g-w boot.log* cron* dmesg httpd/* ksyms* \
#            maillog* messages* pgsql rpmpkgs* samba/* \
#            scrollkeeper.log secure* spooler*                                              2> /dev/null
#      /bin/chmod g-rx boot.log* cron* maillog* messages* pgsql \
#            secure* spooler*                                                                 2> /dev/null
#      /bin/chmod o-w gdm/ httpd/ news/ samba/ squid/ vbox/  dmesg scrollkeeper.log sa lastlog      2> /dev/null
#      /bin/chmod o-rx httpd/ samba/ squid/ sa lastlog dmesg scrollkeeper.log                       2> /dev/null
#      /bin/chmod 600 wtmp* /var/run/utmp*                                                          2> /dev/null
#      /bin/chmod g-w gdm/ httpd/ news/ samba/ squid/ vbox/ sa lastlog dmesg scrollkeeper.log wtmp  2> /dev/null
#      /bin/chmod g-rx httpd/ samba/ sa lastlog                                                     2> /dev/null
#      /bin/chmod o-rwx vbox samba/* rpmpkgs                                                        2> /dev/null
#      /bin/chmod g-rwx samba/* rpmpkgs                                                             2> /dev/null
#      /bin/chmod u-x lastlog                                                                       2> /dev/null
#      /bin/chmod g-rwx,o-rwx /var/log/boot.log                                                     2> /dev/null
#      /bin/chmod g-w,o-w /var/log/gdm                                                              2> /dev/null
#      /bin/chown -R root:root .                                                                    2> /dev/null
#      /bin/chgrp utmp wtmp btmp                                                                    2> /dev/null
#      if [ -e news ]; then /bin/chown -R news:news news;fi
#      if [ -e pgsql ]; then /bin/chown postgres:postgres pgsql;fi
#      if [ -e squid ]; then /bin/chown -R squid:squid squid;fi
#        
#limit the usability of /usr/bin/who
#        /bin/chmod 750 /usr/bin/who
# Fixing "/etc/rc.d/rc.sysinit", as it unsecures permissions for wtmp.
        echo "Section 3.3 completed."
        menu3=1
        flag3=1
    fi

    if test "$automatic" = "1"
    then
        console_in=0
    fi

done
