#!/bin/sh
PATH=$PATH:/bin:/usr/bin:/sbin:/usr/sbin
automatic=$1
options=$2

hardwareUUID=$(/usr/sbin/system_profiler SPHardwareDataType | grep "Hardware UUID" | awk -F ": " '{print $2}')

menu1=0; menu2=0; menu3=0; menu4=0; menu5=0; menu6=0; menu7=0
flag1=0; flag2=0; flag3=0; flag4=0; flag5=0; flag6=0; flag7=0
if test "$automatic" = "1" 
then
    if test "$options" = "1"
    then
        menu1=1; menu2=0; menu3=0; menu4=0; menu5=0; menu6=0; menu7=0
    elif test "$options" = "2"
    then
        menu1=1; menu2=1; menu3=1; menu4=1; menu5=1; menu6=0; menu7=0
    else
        echo "exited in parsing options in section 2 menus"
        exit
    fi
fi
until test "$console_in" = "0"
do
    #clear
    echo "        CIS MACOS Benchmark v2.0"
    echo "             Section 2  Menu"
    echo 
    if test "$menu1" = 1
    then
        echo "_X_ (1) 2.1 Disable Apple File sharing"
    else
        echo "___ (1) 2.1 Disable Apple File Sharing"
    fi
    if test "$menu2" = 1
    then
        echo "_X_ (2) 2.2 Disable SMB File Sharing"
    else
        echo "___ (2) 2.2 Disable SMB File Sharing"
    fi
    if test "$menu3" = 1
    then
        echo "_X_ (3) 2.3 Disable Print Sharing"
    else
        echo "___ (3) 2.3 Disable Print Sharing"
    fi
    if test "$menu4" = 1
    then
        echo "_X_ (4) 2.4 Disable Internet Sharing"
    else
        echo "___ (4) 2.4 Disable Internet Sharing"
    fi
#    if test "$menu5" = 1
#    then
#        echo "_X_ (5) 2.5 Disable Bluetooth Sharing"
#    else
#        echo "___ (5) 2.5 Disable Bluetooth Sharing"
#    fi

    echo "    (0)  Back to Main Menu"
    echo " Selection => "
    
    if test "$automatic" = "1"
        then
        echo "automatic opted"
    else
        read console_in
    fi   

    if ((test "$console_in" = "1" || test "$menu1" = "1" ) && ( test "$flag1" != "1") )
    then
        #launchctl unload com.apple.NetworkSharing
        launchctl stop com.apple.AppleFileServer
        launchctl unload -w /System/Library/LaunchDaemons/com.apple.AppleFileServer.plist
        echo "Section 2.1 completed."
        menu1=1
        flag1=1
    fi

    if ((test "$console_in" = "2" || test "$menu2" = "1") && ( test "$flag2" != "1") )
    then
        launchctl stop com.apple.smbd
        launchctl unload -w /System/Library/LaunchDaemons/com.apple.smbd.plist
        #launchctl unload com.apple.NetworkSharing
        #launchctl stop com.apple.NetworkSharing
        echo "Section 2.2 completed."
        menu2=1
        flag2=1
    fi

    if ((test "$console_in" = "3" || test "$menu3" = "1") && ( test "$flag3" != "1") )
    then
        cupsctl --no-share-printers
        echo "Section 2.3 completed."
        menu3=1
        flag3=1
    fi
    
    if ((test "$console_in" = "4" || test "$menu4" = "1") && ( test "$flag4" != "1") )
    then
        launchctl stop com.apple.NetworkSharing
        launchctl unload -w com.apple.NetworkSharing
        echo "Section 2.4 completed."
        menu4=1
        flag4=1
    fi

    if ((test "$console_in" = "5" || test "$menu5" = "1") && ( test "$flag5" != "1") )
    then
        #launchctl unload com.apple.NetworkSharing
        #launchctl stop com.apple.NetworkSharing
        echo "Section 2.5 completed."
        menu5=1
        flag5=1
    fi
    if test "$automatic" = "1" 
    then
        console_in=0
    fi

done
