#!/bin/bash
#
# - - -
# authority: HHS/CM-7,2
# authority: CIS/8.11
# authority: CIS5/9.10
# description: Examines core-dump entries in limits.conf
# - - -
set -e 

. `dirname $0`/../../lib/functions

check()
{
    # Anything written to stdout or stderr indicates a compliance problem.

    orig_limits=/etc/security/limits.conf
    draft_limits=`scratchfile $orig_limits`

    # Copy orig_limits to draft_limits, tweaking the limits on the way:

    awk '$1 == "*"  && $2 == "soft" && $3 == "core" { $1 = "#*" };
         $1 == "#*" && $2 == "soft" && $3 == "core" && $4 == "0" { $1="*" };

         $1 == "*"  && $2 == "hard" && $3 == "core" { $1 = "#*" };
         $1 == "#*" && $2 == "hard" && $3 == "core" && $4 == "0" { $1="*" };
         
         { print }' $orig_limits >${draft_limits}

    # Add limits to draft_limits if they were not specified:

    if [ `grep -c '^* soft core 0$' ${draft_limits}` -eq 0 ] ; then
        echo "* soft core 0" >> ${draft_limits}
    fi

    if [ `grep -c '^* hard core 0$' ${draft_limits}` -eq 0 ] ; then
        echo "* hard core 0" >> ${draft_limits}
    fi

    # If - after weeding and normalizing - differences would still remain,
    # report all differences between original and draft files.

    grep -v '^ *#' $orig_limits |grep -v '^ *$' | sort|uniq > ${draft_limits}.0 || :
    grep -v '^ *#' $draft_limits |grep -v '^ *$'| sort|uniq > ${draft_limits}.1 || :

    if  diff -bBq "${draft_limits}.0" "${draft_limits}.1" >/dev/null ; then
        rm "${draft_limits}.0" "${draft_limits}.1"
    else
        rm "${draft_limits}.0" "${draft_limits}.1"
        report_diff -b $orig_limits $draft_limits
    fi

}

case "$1" in 
    check)
        check;
        ;;
    *)
        echo "Usage: $0 {check|fix}"
        ;;
esac
exit 0

