#!/bin/bash
#
# - - -
# authority: HHS/IA-2,1
# authority: CIS/7.7
# authority: CIS5/10.1
# description: Checks /etc/issue.net for boilerplate
# - - -
set -e

. `dirname $0`/../../lib/functions

check()
{
    # Anything written to stdout or stderr indicates a compliance problem.

    issue_real=/etc/issue.net
    issue_scratch=$(scratchfile $issue_real)
    cat >$issue_scratch <<EOF
#################################################################
#                      ***WARNING***                            #
# You are accessing a U.S. Government information system, which #
# includes (1) this computer, (2) this computer network, (3) all#
# computers connected to this network, and (4) all devices and  #
# storage media attached to this network or to a computer on    #
# this network.  This information system is provided for U.S.   #
# Government-authorized use only.                               #
# Unauthorized or improper use of this system may result in     #
# disciplinary action, as well as civil and criminal penalties. #
# By using this information system, you understand and consent  #
# to the following.                                             #
#                                                               #
# You have no reasonable expectation of privacy regarding any   #
# communications or data transiting or stored on this           #
# information system.  At any time, and for any lawful          #
# Government purpose, the government may monitor, intercept,    #
# record, and search and seize any communication or data        #
# transiting or stored on this information system.              #
#                                                               #
# Any communication or data transiting or stored on this        #
# information system may be disclosed or used for any lawful    #
# Government purpose.                                           #
#################################################################
EOF
    report_diff $issue_real $issue_scratch

    check_user_group_perms root root 0644 $issue_real
}

case "$1" in 
    check)
        check;
        ;;
    *)
        echo "Usage: $0 {check|fix}"
        ;;
esac
exit 0

