#!/bin/bash
#
# - - -
# authority: Local/1
# description: Checks for "+" NIS entries in /etc/passwd
# - - -
set -e

. `dirname $0`/../../lib/functions

check()
{
    # Anything written to stdout or stderr indicates a compliance problem.

    echo "))= Red flag found ('+' NIS accounts in /etc/passwd):"
    grep ^+ /etc/passwd || :
}

case "$1" in 
    check)
        check;
        ;;
    *)
        echo "Usage: $0 {check|fix}"
        ;;
esac
exit 0

