#!/bin/bash
#
# - - -
# authority: CIS/8.4
# authority: CIS5/9.4
# description: Checks for "+" entries in /etc/shadow
# - - -
set -e

. `dirname $0`/../../lib/functions

check()
{
    # Anything written to stdout or stderr indicates a compliance problem.

    echo "))= Red flag found ('+' accounts in /etc/shadow):"
    grep ^+: /etc/shadow || :
}

case "$1" in 
    check)
        check;
        ;;
    *)
        echo "Usage: $0 {check|fix}"
        ;;
esac
exit 0

