#!/bin/bash
#
# - - -
# authority: CIS5/SN.9
# description: Inspects "net" settings
# - - -
set -e

. `dirname $0`/../../lib/functions

check()
{
    # Anything written to stdout or stderr indicates a compliance problem.

    echo "))= Deviant sysctl values:"
    for keyEqualsExpectedValue in \
        net.ipv4.tcp_max_orphans=256 \
        net.ipv4.conf.all.log_martians=1 \
        ; do
      
      key=$(echo $keyEqualsExpectedValue | cut -d = -f 1 )
      expected_value=$(echo $keyEqualsExpectedValue | cut -d = -f 2 )
      actual_value=$(/sbin/sysctl -n $key)
      if [ "$expected_value" != "$actual_value" ] ; then
          echo "$key = $actual_value (expected: $expected_value)"
      fi
      
    done

    check_user_group_perms root root 0600 /etc/sysctl.conf
}

case "$1" in 
    check)
        check;
        ;;
    *)
        echo "Usage: $0 {check|fix}"
        ;;
esac
exit 0

