#!/bin/bash
#
# - - -
# authority: CIS5/11.1
# description: Checks that sysstat will run automatically

set -e

. `dirname $0`/../../lib/functions

check()
{
    # Anything written to stdout or stderr indicates a compliance problem.

    echo "))= sysstat service is not set to run automatically:"
    check_service sysstat
}

case "$1" in 
    check)
        check;
        ;;
    *)
        echo "Usage: $0 {check|fix}"
        ;;
esac
exit 0

