#!/bin/bash
#
# - - -
# authority: CIS5/11.5
# description: Checks permissions of /usr/share/doc
# - - -
set -e

. `dirname $0`/../../lib/functions

check()
{
    # Anything written to stdout or stderr indicates a compliance problem.

    echo "))= Should be 0644:"
    find /usr/share/doc \( -type f -perm /0033 \) -o \( -type d -perm /0022 \) -ls
}

while [ -n "$1" ] ; do
    case "$1" in 
        check)
            check
            break
            ;;
        *)
            echo "Usage: $0 {check|fix}"
            exit 2
            ;;
    esac
done
exit 0

