#!/bin/bash
#
# - - -
# authority: HHS/CM-7,3
# authority: CIS/3.2
# authority: CIS5/4.2
# description: Checks that xinetd is turned off if none of its services are enabled
# - - -
set -e

. `dirname $0`/../../lib/functions

check()
{
    # Anything written to stdout or stderr indicates a compliance problem.

    # In RHEL6, /etc/xinetd.d exists even if xinetd itself is not installed!
    if [ -d /etc/xinetd.d -a -f /etc/init.d/xinetd ] ; then
        cd /etc/xinetd.d 
        if [ "`/sbin/chkconfig --list xinetd | grep -c :on`" != "0" ] ; then
            if [ $(awk '($1=="disable" &&$3=="no"){print}' * |wc -l) == "0" ] ; then 
                echo xinetd is configured to run in at least one runlevel, but no service needs it.
            fi
        fi 
    fi

}

case "$1" in 
    check)
        check;
        ;;
    *)
        echo "Usage: $0 {check|fix}"
        ;;
esac
exit 0
